name = "autumn-limit-001e-3"
main = "worker3.js"
compatibility_date = "2024-04-01"



# 🗄️ D1 에지 데이터베이스 바인딩 설정
[[d1_databases]]
binding = "DB"
database_name = "backtest-db"
database_id = "c8422418-0114-4c3a-9bd5-c4ee71d4da07"

# ⚡ KV 네임스페이스 바인딩 설정
[[kv_namespaces]]
binding = "VTOTAL_KV"
id = "65636562b33a42c38bb16284c3b3d6cc"
